image: golang:alpine
stages:
  - test

before_script:
  - go get github.com/golang/dep
  - ln -s /builds /go/src/git.platform.manulife.io/oa-montreal
  - cd /go/src/git.platform.manulife.io/oa-montreal/${CI_PROJECT_PATH}

test-repo:
  stage: test
  script:
    - dep ensure -v -update
    - go test -v -cover -race ./...

