version: "3"

services:
  redis:
    container_name: sparkles-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      sparklesnet:
        aliases:
          - redis.sparkles.local

  sparkles:
    container_name: psparkles
    image: peppermint-sparkles:latest
    depends_on:
      - redis
    ports:
      - "9001:8080"
    networks:
      - sparklesnet
    command: ["serve", "-dst", "redis", "-dsa", "redis.sparkles.local:6379"]
    environment:
      - LOGGER_LEVEL=debug

networks:
  sparklesnet:
    driver: bridge
