---

groups:
- name: {{APP_NAME}}
  jobs:
  - unit-test-uat
  - deploy-uat
  - unit-test-prod
  - deploy-prod

resource_types:
- name: artifactory
  type: docker-image
  source:
    insecure_registries: ["10.234.24.211:443"]
    repository: 10.234.24.211:443/artifactory-resource

resources:
- name: binary-repo
  type: artifactory
  source:
    endpoint: {{ARTIFACTORY_URI}}
    repository: {{ARTIFACTORY_REPO}}
    regex: "peppermint-sparkles-v(?<version>[0-9].[0-9].[0-9]).tar.bz2"
    username: {{ARTIFACTORY_USER}}
    password: {{ARTIFACTORY_PASS}}
    skip_ssl_verification: true

- name: git-source-uat
  type: git
  source:
    branch: {{GIT_BRANCH}}
    tag_filter: "*.uat"
    uri: {{GIT_URI}}
    private_key: {{GIT_PRIVATE_KEY}}
    skip_ssl_verification: true

- name: pcf-uat
  type: cf
  source:
    api: {{PCF_API}}
    username: {{PCF_UAT_USER}}
    password: {{PCF_UAT_PASS}}
    organization: GSD-CAC-UAT
    space: OA-MONTREAL-CAC-UAT
    skip_cert_check: true

- name: git-source-prod
  type: git
  source:
    branch: master
    uri: {{GIT_URI}}
    private_key: {{GIT_PRIVATE_KEY}}
    skip_ssl_verification: true

- name: pcf-prod
  type: cf
  source:
    api: {{PCF_API}}
    username: {{PCF_PROD_USER}}
    password: {{PCF_PROD_PASS}}
    organization: GSD-CAC-PROD
    space: OA-MONTREAL-CAC-PROD
    skip_cert_check: true

jobs:
# UAT environment
- name: unit-test-uat
  public: true
  plan:
  - get: peppermint-sparkles
    resource: git-source-uat
    trigger: true
  - task: unit
    file: peppermint-sparkles/ci/tasks/unit_test.yml

- name: deploy-uat
  public: true
  serial: true
  plan:
  - get: peppermint-sparkles
    resource: git-source-uat
    trigger: true
    passed: [unit-test-uat]
  - get: peppermint-sparkles/build/bin
    resource: binary-repo
  - task: redis
    file: peppermint-sparkles/ci/tasks/redis_service.yml
    params:
      TERM: xterm
      CF_API: {{PCF_API}}
      CF_USER: {{PCF_UAT_USER}}
      CF_PASSWORD: {{PCF_UAT_PASS}}
      CF_ORG: GSD-CAC-UAT
      CF_SPACE: OA-MONTREAL-CAC-UAT
      REDIS_PLAN: shared-vm
      REDIS_NAME: rainbow-dash-redis
  - put: pcf-uat
    params: 
      manifest: peppermint-sparkles/pcf/uat_manifest.yml

# PROD environment
- name: unit-test-prod
  public: true
  plan:
  - get: peppermint-sparkles
    resource: git-source-prod
    trigger: true
  - task: unit
    file: peppermint-sparkles/ci/tasks/unit_test.yml

- name: deploy-prod
  public: true
  serial: true
  plan:
  - get: peppermint-sparkles
    resource: git-source-prod
    passed: [unit-test-prod]
  - get: peppermint-sparkles/build/bin
    resource: binary-repo
  - task: redis
    file: peppermint-sparkles/ci/tasks/redis_service.yml
    params:
      TERM: xterm
      CF_API: {{PCF_API}}
      CF_USER: {{PCF_PROD_USER}}
      CF_PASSWORD: {{PCF_PROD_PASS}}
      CF_ORG: GSD-CAC-PROD
      CF_SPACE: OA-MONTREAL-CAC-PROD
      REDIS_PLAN: dedicated-vm
      REDIS_NAME: rainbow-dash-redis
  - put: pcf-prod
    params: 
      manifest: peppermint-sparkles/pcf/prod_manifest.yml
